### ISSUE TITLE
v0.1.4： 打不开设置界面

### ISSUE THREAD

**Issue by sumspec** [ppoffice/Hozz#42]
windows10 x64版本 不能进入设置页面
![Uploading screenshot_20170508184235.png…]()

**Comment by ppoffice** [comment]
@sumspec 
请备份用户目录下的`.Hozz`文件夹后删除这个文件夹，再重新添加hosts。
另外请贴一下此文件夹下的log.txt中最近几次记录。

**Comment by sumspec** [comment]
这是最近两次的日志：

[2017-5-8 18:42:2.634]
r: request to https://raw.githubusercontent.com/racaljk/hosts/master/hosts
failed, reason: connect ETIMEDOUT 151.101.88.133:443
    at ClientRequest.<anonymous>
(file:///C:/Program%20Files/Hozz/resources/app/main.js:1:344074)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:265:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
[2017-5-10 14:13:54.299]
r: request to https://raw.githubusercontent.com/sy618/hosts/master/FQ
failed, reason: read ECONNRESET
    at ClientRequest.<anonymous>
(file:///C:/Program%20Files/Hozz/resources/app/main.js:1:344074)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:265:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)

这是软件界面 设置界面只有一个框架 点不开 下图

​

2017-05-08 19:09 GMT+08:00 Ruipeng Zhang <notifications@github.com>:

**Comment by ppoffice** [comment]
@sumspec 
能麻烦您到`软件安装目录\resources\app\browser.js`里把[这句话](https://github.com/ppoffice/Hozz/blob/master/src/browser.js#L144)的注释去掉然后重新运行程序，将调试窗口中的错误贴在这里么？谢谢。

**Comment by ghost** [comment]
@ppoffice 
# 现在能打开设置了
😐w10任务栏图标都是合并的，打开主界面点设置关主界面，点两下任务栏按钮就看到设置了。
关闭合并图标，只要点设置窗口的任务栏按钮就能打开。
感谢@imaqine [https://github.com/ppoffice/Hozz/issues/40](url)
最后，再把调试窗口独立出来之后发现每次打开再关闭设置窗口之后总有这个
![image](https://user-images.githubusercontent.com/31348644/29721568-4c2b8068-89f0-11e7-8914-e4644908ad99.png)

## 其他
窗口出现的好慢，其实比慢更奇怪，双击打开首先看不到任何东西，但其实是有“透明面板”的，除了全透明貌似一切正常，在一段时间后 最大最小化/右键通知图标点hozz/找到窗口边缘光标变成调整窗口大小后进行调整/…… 就能显示界面。

PS：实测设置界面变成透明面板，鼠标挪来挪去找到了能点的“小手指”，试着在虚空里挪一下窗口，小手指位置也变了
![default](https://user-images.githubusercontent.com/31348644/29720087-50c269fc-89eb-11e7-8ea7-61fb77478a8a.png)

### ,Hozz\log

>[2017-8-25 21:54:17.334]
Error: EBUSY: resource busy or locked, open 'C:\Windows\system32\drivers\etc\hosts'
    at Error (native)
[2017-8-25 21:54:48.632]
Error: EBUSY: resource busy or locked, open 'C:\Windows\system32\drivers\etc\hosts'
    at Error (native)
[2017-8-25 22:18:12.953]
Error: EBUSY: resource busy or locked, open 'C:\Windows\system32\drivers\etc\hosts'
    at Error (native)
[2017-8-25 22:22:17.609]
Error: EBUSY: resource busy or locked, open 'C:\Windows\system32\drivers\etc\hosts'
    at Error (native)

**Comment by aogg** [comment]
+1 并选择弃用
